[programs.localnet]
mpl_nft_machine = "6J7avjMHMQMDz8JVERqSxXseChTCKjrfiPh6KFTqJxdN"
[programs.devnet]
mpl_nft_machine = "6J7avjMHMQMDz8JVERqSxXseChTCKjrfiPh6KFTqJxdN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/wstar/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
